# Instructions ----
#' This file follows the format generated by ecosystemdata:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemdata:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# load_model ----
## IO correctness ----
functional_groups <- c(
  "StripedBass0", "StripedBass2_5", "StripedBass6",
  "AtlanticMenhaden0", "AtlanticMenhaden1", "AtlanticMenhaden2", "AtlanticMenhaden3",
  "AtlanticMenhaden4", "AtlanticMenhaden5", "AtlanticMenhaden6",
  "SpinyDogfish",
  "BluefishJuvenile",
  "BluefishAdult",
  "WeakfishJuvenile",
  "WeakfishAdult",
  "AtlanticHerring0_1", "AtlanticHerring2",
  "Anchovies",
  "Benthos",
  "Zooplankton",
  "Phytoplankton",
  "Detritus"
)

model_years <- 1985:2017

test_that("load_model() works with correct inputs", {
  ewe_model <- load_model(
    directory = fs::path("data-raw", "ewe_nwatlantic", "base_run"),
    functional_groups = functional_groups, 
    type = "ewe"
  )
  
  expected_colnames <- c(
    "file_name", "type", "year", "month", "functional_group", "value", "fleet"
  )
  #' @description Test that load_model() returns correct columns.
  expect_equal(
    object = colnames(ewe_model),
    expected = expected_colnames
  )

  #' @description Test that load_model() returns correct type of output.
  expected_types <- c(
    "biomass", "catch", "landings", "weight"
  )
  expect_equal(
    object = ewe_model |> dplyr::pull(type) |> unique(),
    expected = expected_types
  )

  #' @description Test that load_model() returns correct number of rows.
  no_landings_nrow <- ewe_model |>
    dplyr::filter(type != "landings") |>
    nrow()
  expected_nrow <- 12 * length(model_years) * length(functional_groups) * (length(expected_types) - 1)
  expect_equal(
    object = no_landings_nrow,
    expected = expected_nrow
  )
})

## Edge handling ----
test_that("load_model() returns correct outputs for edge cases", {
  #' @description Test that load_model() without functional_groups returns an error.
  expect_error(
    object = load_model(
      directory = fs::path("data-raw", "ewe_nwatlantic", "base_run"),
      type = "ewe"
    ),
    regexp = "is missing, with no default"
  )
  #' @description Test that load_model() without directory returns an error.
  expect_error(
    object = load_model(
      functional_groups = functional_groups,
      type = "ewe"
    )
  )
})

## Error handling ----
test_that("load_model() returns correct error messages", {
  #' @description Test that load_model(x) returns expected error.
  expect_error(
    object = load_model("atlantis"),
    regexp = "is not yet configured for"
  )
})
