# Instructions ----
#' This file follows the format generated by ecosystemdata:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemdata:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----
# Load or prepare any necessary data for testing
# Read in amo data
amo_data <- read.csv(
  file = fs::path(
    system.file("extdata", package = "ecosystemdata"),
    "ewe_nwatlantic", "environmental_link", "amo_lag1.csv"
  )
)

# Read in palmer_drought_severity_index.csv
pdsi_data <- read.csv(
  file = fs::path(
    system.file("extdata", package = "ecosystemdata"),
    "ewe_nwatlantic", "environmental_link", "pdsi_lag0.csv"
  )
)

# reshape_environment_data ----
## IO correctness ----
test_that("reshape_environment_data() works with correct inputs", {
  object <- reshape_environment_data(
    index_name = "amo",
    values = amo_data[["value"]],
    years = 1984:2016,
    lag = 1,
    impacted_group = "menhaden 0"
  ) |>
    dplyr::bind_rows(
      reshape_environment_data(
        index_name = "pdsi",
        values = pdsi_data[["value"]],
        years = 1985:2017,
        lag = 0,
        impacted_group = "phytoplankton"
      )
    )

  #' @description Test that the function returns a tibble with the correct number of rows.
  expect_equal(
    object = nrow(object),
    expected = nrow(amo_data) + nrow(pdsi_data)
  )

  #' @description Test that the function returns correct snapshot.
  expect_snapshot(
    print(object, n = nrow(object))
  )

  #' @description Test that the function returns a tibble with expected column names.
  expect_equal(
    object = colnames(object),
    expected = c(
      "index_name", "value", "year", 
      "month", "lag", "impacted_group",
      "species", "group"
    )
  )
})

## Edge handling ----
# No edge cases for now.

## Error handling ----
test_that("reshape_environment_data() returns correct error messages", {
  #' @description Error when length of values does not match years * 12.
  expect_error(
    object = reshape_environment_data(
      index_name = "amo",
      values = c(0.1, 0.2, 0.3),
      years = 1984:1985,
      lag = 1,
      impacted_group = "menhaden 0"
    ),
    regexp = "Length mismatch between `values` and expected time steps"
  )

  #' @description Error when index_name is not a single character string.
  expect_error(
    object = reshape_environment_data(
      index_name = c("amo", "pdsi"),
      values = amo_data[["value"]],
      years = 1984:2016,
      lag = 1,
      impacted_group = "menhaden 0"
    ),
    regexp = "`index_name` must be a single character string"
  )

  #' @description Error when values is not a numeric vector.
  expect_error(
    object = reshape_environment_data(
      index_name = "amo",
      values = "not a numeric vector",
      years = 1984:2016,
      lag = 1,
      impacted_group = "menhaden 0"
    ),
    regexp = "`values` must be a numeric vector"
  )

  #' @description Error when years contains non-integer values.
  expect_error(
    object = reshape_environment_data(
      index_name = "amo",
      values = amo_data[["value"]],
      years = c(1984, 1985, 1986.5),
      lag = 1,
      impacted_group = "menhaden 0"
    ),
    regexp = "`years` must be an integer vector"
  )

  #' @description Error when lag is not a single numeric value.
  expect_error(
    object = reshape_environment_data(
      index_name = "amo",
      values = amo_data[["value"]],
      years = 1984:2016,
      lag = c(1, 2),
      impacted_group = "menhaden 0"
    ),
    regexp = "`lag` must be a single numeric value"
  )

  #' @description Error when impacted_group is not a single character string.
  expect_error(
    object = reshape_environment_data(
      index_name = "amo",
      values = amo_data[["value"]],
      years = 1984:2016,
      lag = 1,
      impacted_group = c("menhaden 0", "menhaden 1")
    ),
    regexp = "`impacted_group` must be a single character string"
  )
})
