# Runs devtools::spell_check().
name: call-spell-check

on:
  pull_request:
    branches:
      - main
  push:
    # TODO: uncomment following lines once tests are passing
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/spell-check.yml@main