# Runs R CMD CHECK on the package.
name: call-r-cmd-check

on:
  push:
  workflow_dispatch:

jobs:
  # Install git LFS and pull the data
  install-git-lfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install git-lfs
        run: |
          git lfs pull
  call-workflow:
    uses: nmfs-ost/ghactions4r/.github/workflows/r-cmd-check.yml@main
    with: 
      gha_timeout_minutes: 60