# Runs allcontributors::add_contributors() to add, or update, an alphabetized
# list of contributors to the README.md file and open a new PR with those
# changes.
name: call-r-cmd-check

on:
  push:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: NOAA-FIMS/FIMS/.github/workflows/pr-checklist.yml@main